### ISSUE TITLE
RFC: TPAC meeting structure

### ISSUE THREAD

**Issue by LJWatson** [w3c/webappswg#10]
WebApps will meet on the Thursday and Friday of [TPAC week](https://www.w3.org/2019/09/TPAC/schedule.html) (16 to 20 September 2019).
    
To   make the most of our time together, we're proposing an unconference style structure for the two days. The unconference sessions can be whatever we want them to be; work groups for a particular specification or workshops on things like writing tests or using Respec for example.

Please let us know what you think of the following outline.

#### Thursday 19 September
* 9:00am Welcome, introductions and administrivia
* 9:30am Specification status reports (Editors):
  * What progress has your spec made in the last year?
   * Is anything blocking your spec from moving to CR?
   * If there is a blocker, what is your plan for unblocking and how can the Chairs/WG help?
   * What do you want to achieve over the next two days?
   * Is there anyone in the room you want to co-ordinate with and/or anything you want to learn about?
* 10:45am Break
* 11:15am Unconference logistics
* 11:45am Unconference sessions (Everyone)
1:00pm Suggested lunch break
2:00pm Unconference sessions resume
3:30pm Suggested break
4:00pm Unconference sessions resume
5:30pm End

#### Friday 20 September
* 9:00am Unconference logistics (Everyone)
* 9:30am Unconference sessions (Everyone)
* 1045am Suggested break
* 11:15am Unconference sessions resume
* 1:00pm Suggested lunch
* 2:00pm Unconference sessions resume
* 3:00pm Suggested break
* 3:30pm Wrap up (Everyone)
  * Report from each work group/workshop
* 4:30pm End

#### Remote
Join WebEx meeting
[https://mit.webex.com/mit/j.php?MTID=mb50a6101cbdf6c7040a9f5f26d20c77c](https://mit.webex.com/mit/j.php?MTID=mb50a6101cbdf6c7040a9f5f26d20c77c)
Meeting number:	646 056 738
Meeting password:	check this [member-only archive](https://lists.w3.org/Archives/Member/w3c-archive/2019Sep/0159.html) or ask our co-chairs
Join from a video conferencing system or application
Dial 646056738@mit.webex.com
You can also dial 173.243.2.68 and enter your meeting number.

Join by phone
+1-617-324-0000 US Toll Number
Access code: 646 056 738
Mobile Auto Dial:+1-617-324-0000,,,646056738#

[Add to your calendar](https://mit.webex.com/mit/j.php?MTID=me7e2988748019ffea073e4866fb62e08)

**Comment by LJWatson** [comment]
We'll need to set aside some time to meet with other WG should they request it. I can send a notice to chairs@ to ask that requests for joint meeting time are with us by a certain date, so we can plan accordingly?

**Comment by marcoscaceres** [comment]
How about we tentatively set aside 1 hour on Friday after lunch? That would be least disruptive, and we can reclaim the time if no one wants to meet.

**Comment by LJWatson** [comment]
Have sent an email to all chairs, asking that they let us know by 26 July if they would like to meet with us.

**Comment by szager-chromium** [comment]
Is there a forum for listing issues we'd like to discuss at TPAC, so that participants have a chance to read up and prepare beforehand? Unconference style is fine and all, but we can end up wasting a lot of  time if everyone goes in completely cold.

**Comment by LJWatson** [comment]
Suggest tracking issues for discussion on the repo for the spec in 
question, then referencing that issue here.

**Comment by anssiko** [comment]
>We'll need to set aside some time to meet with other WG should they request it.

DAS WG would like to borrow your co-chair @marcoscaceres for some Wake Lock API discussions Thu around 4pm. Our plans are baking at https://github.com/w3c/devicesensors-wg/issues/24 Other WebApp-ers are also welcome to pop in if the topics look interesting.

**Comment by marcoscaceres** [comment]
@anssiko, I should be able to sneak away for a bit.

**Comment by szager-chromium** [comment]
IntersectionObserver should be about ready for CR, but there are a few issues to tie up, which I'm hoping to schedule time for at TPAC:

https://github.com/w3c/IntersectionObserver/issues/380

**Comment by gked** [comment]
Would it be possible to add an agenda item for Thursday? MS Edge team would like to discuss a super low latency cursor-trail API to get best available ink latency offered by a given platform. https://github.com/w3c/pointerevents/issues/204#issuecomment-527656843. @dlibby- as FYI.

**Comment by rniwa** [comment]
Hi, just as FYI, I won't be able to come to the meeting until 10:00am - 10:15am today.

**Comment by marcoscaceres** [comment]
No problem. Thanks for letting us know.
