### ISSUE TITLE
TPAC 2024 Face to Face meeting

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webappswg#109]
As we approach the W3C TPAC 2024, we wanted to share some important details regarding our upcoming face-to-face meeting:

**TPAC 2024 Dates:**
23-27 September 2024 - Anaheim, CA, USA - See: https://www.w3.org/news-events/w3c-tpac/

**Web Applications Working Group Meeting:**
Dates: (TENTATIVE) Monday, 23rd September and Friday, 27th September - all day.

To help us prepare for our meeting, we will be using the label "TPAC2024" on each repository to identify discussion topics.

**Important Deadlines:**

- Please label all relevant issues by the first week of September.
- Chairs will put together the agenda by the 13th of September to give everyone attending time to review the topics.

And don’t worry, we will send periodic reminders through the next few months to remind everyone!

Nevertheless, we encourage everyone to start thinking about topics for discussion and to begin reaching out and coordinating among yourselves on the topics you would like to discuss face-to-face. September is not that far away.

Additionally, we will be coordinating with the Device and Sensors Working Group for joint deliverables (date not set yet).

To ensure we have an appropriate room size, please indicate your attendance by giving a thumbs up on this issue if you plan to attend in person.

If you have any questions or need further information, please do not hesitate to reach out.

Looking forward to seeing you at TPAC 2024!

**Comment by LJWatson** [comment]
>Our working groups meeting will be on (TENTATIVE) Monday 23rd - Friday 27th.

Does this mean Mon, Tue, Thu, and Fri; or Mon and Fri; or something else?

**Comment by marcoscaceres** [comment]
Oops, sorry for the lack of clarity. Just Monday and Friday.

**Comment by LJWatson** [comment]
NP, and thanks for the calrification. That WFM.

**Comment by marcoscaceres** [comment]
Updated https://github.com/w3c/webappswg/issues/109#issue-2282947598 with latest information.

**Comment by marcoscaceres** [comment]
@anssiko, @reillyeon, does one of the above days work for @w3c/das-wg? We could set aside 90mins to go through the joint deliverables.

**Comment by anssiko** [comment]
Monday is a full day for me and I expect Reilly too (WebML WG). Friday people usually start to leave early. Thursday could accommodate joint deliverables discussion the best assuming no other conflicts. We could flexibly shift to a time slot within that day that works for interested people. It is quite a challenge to get all these meetings lined up nicely.

**Comment by christianliebel** [comment]
Unfortunately, I can't attend in person this year. I'll join remotely, and WebApps is my priority, so any date is fine with me.

**Comment by marcoscaceres** [comment]
>  Friday people usually start to leave early.

We could do first thing Friday. The number of people involved in the join deliverables is small regardless, and the number of issues are small. 

I can't promise to be available on any other day, as I'm chairing Media WG on Thursday. 

(also, if we let folks know we are doing things on Friday that matter, they won't/shouldn't leave early... TPAC runs the whole week)

**Comment by anssiko** [comment]
I'm chairing the Second Screen WG on Friday. Maybe during the breakout day then?

**Comment by reillyeon** [comment]
I'm not sure the TPAC organizers will even let us schedule a joint meeting on the breakout day as it would use up a room that would otherwise be available for breakouts. I also personally find the breakouts the most exciting part of the week (sorry) and wouldn't want to miss it.

Anssi, can we split both the DAS the Second Screen WG meetings across Thursday and Friday (e.g. DAS in the morning and Second Screen in the afternoon) so that there's an opportunity for a Friday overlap with WebApps to discuss joint deliverables?

**Comment by LJWatson** [comment]
@reillyeon those are good points. 

What we need is a time machine...

Failing that, if Reilly's  plan in https://github.com/w3c/webappswg/issues/109#issuecomment-2125426255 isn't workable, @marcoscaceres is there any chance you could spare an hour or so out of Digital Identity on Thursday? I think I should be able to make time then - specially if it was in the morning (the afternoon carries the risk of an AC meeting being scheduled which I really can't step out of).

**Comment by marcoscaceres** [comment]
No, unfortunately. I’m the primary editor of the Digital Credentials spec, so need to be there the whole time. 

Anyway, there may be that there’s nothing to discuss in person jointly. I’m happy to field questions about the joint deliverables along with editors that might show up to WebApps. 

We don’t need to have 4 Chairs there, specially if we are discussing technical matters.

**Comment by marcoscaceres** [comment]
close, @reillyeon! Confusingly, the Digital Credentials stuff is happening in the FedID WG. But, some of the date/times the same as the VC group. 

So, we could potentially make it work for Friday afternoon. 

Primary thing I would like to discuss is how we merge the relevant X Sensor specs from DAS into the joint deliverables so we don’t have multiple competing specs that effectively do the same thing.

**Comment by LJWatson** [comment]
Unless I'm missing something in the draft schedule, of all the CG/WG we collectively have unavoidable commitments to, only DAS is meeting between 9AM and 10:30AM on Tuesday, so could we take 45 to 60 mins then perhaps?

The FedID CG and FedID WG meetings don't start until 11AM on Tuesday. The Media, Second Screen, WebML, Verifiable Creds, or WebApps WG do not meet on Tuesday at all.

Another possibility is the 4:30PM to 6PM slot on Tuesday. Note though that I would only be able to make the last 45 mins of that time because the AC meeting is 2PM to 5PM on Tuesday afternoon).

**Comment by marcoscaceres** [comment]
Ok, yeah, we could grab that Tuesday morning slot. We can go and meet in the DAS room I guess. 

The challenge will be getting WebApps members over to DAS, as what we actually need is DAS to come and talk to WebApps.

**Comment by LJWatson** [comment]
Providing @anssiko and @reillyeon don't mind us borrowing a bit of the DAS meeting time for a joint DAS and WebApps meeting, I think this is our best bet. They're joint deliverables so whether WebApps goes to DAS or vice versa, probably won't make any difference - there will always be some who're unable to attend for various reasons.

**Comment by anssiko** [comment]
@LJWatson, thank you for identifying this slot.

We look forward to meeting WebApps WG participants between 9AM and 10:30AM on Tuesday (2024-09-24). That slot works the best also for the expected DAS WG remote participants.

@alexandralacourba, this is about DAS WG and WebApps WG joint meeting, numbers 17 and 40 in the draft schedule rolled into one: 9AM and 10:30AM on Tuesday (2024-09-24). DAS WG will borrow that slot for a joint meeting and we will commence with DAS WG from 11:00A onwards on Tuesday.

**Comment by alexandralacourba** [comment]
Ok @anssiko , Do you then confirm that we should delete the slots assigned on Thursday for this joint meeting?:
Thursday, 09:00 - 10:30, joint meeting with Web Applications WG (#17)
Thursday, 14:00 - 16:00, joint meeting with Web Applications WG (#40)

**Comment by anssiko** [comment]
@alexandralacourba correct, those two joint meeting slots will be deleted and rolled into one as follows:

```
Devices and Sensors WG
Tuesday, 09:00 - 10:30, joint meeting with Web Applications WG
Tuesday, 11:00 - 18:00 (#39)

```

**Comment by alexandralacourba** [comment]
Ok, we will do the modification. Thank you!

**Comment by marcoscaceres** [comment]
Closing as we have put the aganda in the wiki:
https://github.com/w3c/webappswg/wiki/TPAC-2024


And notified the working group via [public-webapps](https://lists.w3.org/Archives/Public/public-webapps/2024JulSep/0010.html).
