### ISSUE TITLE
"not authorized" to publish pointer lock

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webappswg#11]
The spec is all good, but getting the following... adding here as a reminder. 
https://lists.w3.org/Archives/Public/public-tr-notifications/2019Jun/0019.html

**Comment by marcoscaceres** [comment]
@siusin know you are working on getting the new token working - no hurry. Just wanted to track it.

**Comment by siusin** [comment]
Lesson learnt: it's better to add the encrypted token as global env in the .travis.yml, if we are using it in the travis settings, it won't be encrypted.
