### ISSUE TITLE
TPAC 2024: Adding IndexedDB to the agenda

### ISSUE THREAD

**Issue by SteveBeckerMSFT** [w3c/webappswg#111]
Is it possible to add IndexedDB to the Web Applicaitons Working Group's agenda?

I proposed a list of IndexedDB discussion topics:
https://github.com/w3c/IndexedDB/issues?q=label%3ATPAC2024

I also created this issue to discuss the meetup.
https://github.com/w3c/IndexedDB/issues/422

Please let me know what else we need to add IndexedDB to the agenda.  Thanks!

**Comment by saschanaz** [comment]
#109 is closed last month, I wonder this be too late to be added, although looks interesting. That said, not all in the list have any topic marked as TPAC2024...

**Comment by SteveBeckerMSFT** [comment]
We discussed IndexedDB in the Web App WG on 9/23.  I'll publish a report that summarizes in the [IndexedDB github issues](https://github.com/w3c/IndexedDB/issues).
