### ISSUE TITLE
uievents missing .travis file 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webappswg#12]
The uievents repo is missing .travis.yml file with BikeShed auto publish magic. It's probably then missing all the other stuff needed to generate the BikeShed document. 

https://github.com/w3c/uievents

@siusin, could you set this one up?

**Comment by siusin** [comment]
@marcoscaceres they are using a [python script](https://github.com/w3c/uievents/blob/gh-pages/build.py) to generate the spec. I'll check if we can convert that script into yml script.

**Comment by marcoscaceres** [comment]
Thanks! I see it’s the same the keys and codes specs too. So hopefully that will cover all three.

**Comment by siusin** [comment]
[UI Events KeyboardEvent key Implementation Report](https://w3c.github.io/uievents-key/impl-report.html)
[UI Events KeyboardEvent code Implementation Report](https://w3c.github.io/uievents-code/impl-report.html)
