### ISSUE TITLE
Contact editors to prepare for TPAC

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webappswg#13]
In first week of August, we should reach out to editors in preparation for TPAC to get a status update, and see if they can nominate someone to represent each spec at TPAC itself.

**Comment by szager-chromium** [comment]
Did this happen?

**Comment by marcoscaceres** [comment]
I thought it did... checking

**Comment by marcoscaceres** [comment]
https://lists.w3.org/Archives/Public/public-webapps/2019JulSep/0016.html

**Comment by LJWatson** [comment]
I was going to file an issue on each spec repo as a prompt, but haven't 
had time to get to it yet.
