### ISSUE TITLE
Indexed DB in list of specs?

### ISSUE THREAD

**Issue by inexorabletash** [w3c/webappswg#22]
Should IDB be on the list? Or did I miss something...?

**Comment by inexorabletash** [comment]
In this repo's top level README.md I mean.

**Comment by LJWatson** [comment]
IDB3.0 will need to publish an FPWD before it'll show up on the 
[homepage](https://w3c.github.io/webappswg/).

**Comment by inexorabletash** [comment]
Ah. Well then, shame on me.

**Comment by LJWatson** [comment]
Is IDB3 anywhere near to being able to go for FPWD do you think? Once we've done that, we can automate WD updates based on commits with the ED, which is altogether much simpler.

**Comment by inexorabletash** [comment]
We could go to FPWD any time, although I expect substantial changes before we decide to advance further. Happy to confirm that tomorrow at the meeting.

(Since we review things prior to merging into ED, the practical distinction between ED/WD distinction is minimal.)
