### ISSUE TITLE
Send a CFC for Screen Orientation spec to go to CR

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webappswg#24]
The Screen Orientaiton spec is more or less CR ready. Need to double check with @mounirlamouri that he is ok with it :)

**Comment by mounirlamouri** [comment]
I'm fine with that. We may want to resolve the timing issue first -- or at least before REC.

**Comment by marcoscaceres** [comment]
We are blocked on not having time to get back to this... both on the spec side and on the implementation side.

**Comment by marcoscaceres** [comment]
No update yes... but maybe @mounirlamouri and I can find two hours to meet 😇🙏(💵💰)

**Comment by marcoscaceres** [comment]
Closing this. Will handle all this over in the spec when it's ready.
