### ISSUE TITLE
Initiate wide review of Web Share API

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webappswg#27]
I've send a request to publish the Web Share API as a FPWD, so be nice to initiate wide review. @LJWatson, as you have most experience with initiating those, could you take this? 

The URL for the Web Share API editor's draft is: https://w3c.github.io/web-share/

**Comment by marcoscaceres** [comment]
@LJWatson will try to kick this off soon.

**Comment by LJWatson** [comment]
Requests filed for:
* I18n at w3c/i18n-request#129
* TAG at w3ctag/design-reviews#554
* A11y by [email to APA WG](https://lists.w3.org/Archives/Public/public-apa/2020Aug/0021.html)
* Privacy by [email to Privacy IG](https://lists.w3.org/Archives/Public/public-privacy/2020JulSep/0028.html)
* Security by email to @samuelweiler
* General public by [tweet](https://twitter.com/LeonieWatson/status/1299680555999670272)
* General review by [email to public-review-announce](https://lists.w3.org/Archives/Public/public-review-announce/2020Aug/0012.html)

**Comment by marcoscaceres** [comment]
Cool, let's consider this done.

**Comment by saschanaz** [comment]
Why reopening then? 👀

**Comment by LJWatson** [comment]
> Why reopening then? 👀

So we can track progress on the reviews.

**Comment by marcoscaceres** [comment]
Wide reviews done... closing
