### ISSUE TITLE
Look at progressing IntersectionObserver 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webappswg#29]
What do we need to do to get IntersectionObserver to CR?

**Comment by marcoscaceres** [comment]
We need to check the TPAC minutes and we might be able to get V1 out as CR.

**Comment by marcoscaceres** [comment]
@LJWatson will follow up with the editor...

**Comment by marcoscaceres** [comment]
@LJWatson tried to follow up... no response yet. But will try again... 

@marcoscaceres trying to find someone from Mozilla...

**Comment by marcoscaceres** [comment]
Sent PR: https://github.com/w3c/IntersectionObserver/pull/441

**Comment by szager-chromium** [comment]
I'm sorry for the long radio silence. It has been on my to-do list to spend time going through the issues, but I am prone to starving tasks when the list gets too long.

I'm not sure if there's anyone else to step in as editor; but I will rededicate myself to going through the issue tracker in the coming week.

**Comment by marcoscaceres** [comment]
@Emilio will work together with @szager-chromium editing the spec.
