### ISSUE TITLE
Send out meeting proposal once everyone rejoins

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webappswg#3]
Day 1: 

* 9:00 - 9:30am: welcome, introductions, and administrivia. Talk a bit about the change in working mode - make sure it's clear. 
* 9:30 - 10:45am: go around the room and get status on each spec (~5min per spec). I'd expect a designated spec editor to answer the following questions:

1. What progress have you made in the last year? 
2. Is anything blocking the specification from making progress towards CR? 
3. If something is blocking, what is your plan to unblock - And What can the Chairs or WG do to help?
4. What do you hope to achieve over the next 2 days?
5. Is there anyone else in the room you need to coordinate with or anything you'd like to learn more about?

10:45-11:15 AM - unconference logistics. Let people form groups and go work on stuff. If people want to run small workshops (e.g., how to write tests, how to use ReSpec, how to whatever), we can run those too.   

11:15am-5:00pm Breakout sessions. People break off and go work together on their specs - resolve issues, debate ideas, etc.

Day 2: 

9:00am - 9:30AM unconference logistics.
9:30am - 3:00pm Breakout sessions
3:00pm - 4pm Wrap up, go around the room and find out: 

- What did you resolve or achieve during the meeting? 
- What's your plan to move your spec forward to CR in the next year?

**Comment by LJWatson** [comment]
Closed with #10
