### ISSUE TITLE
Publish ImageResource spec

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webappswg#30]
@siusin or @ylafon, we want to extract something that lived in the Web Manifest spec into its own spec (`ImageResource`):

https://github.com/w3c/image-resource

What do we need to do to publish that as a FPWD? 

cc @rayankans @aarongustafson 

- [x] must record the group’s decision to request advancement.
- [ ] must obtain Director approval.
- [x] must publicly document all new features (class 4 changes) to the technical report since the previous publication.
- [x] must publicly document if other substantive changes (class 3 changes) have been made, and should document the details of such changes.
- [x] should publicly document if editorial changes have been made, and may document the details of such changes.
- [ ] must formally address all issues raised about the document since the previous maturity level.
- [ ] must provide public documentation of any Formal Objections.
- [ ] should report which, if any, of the Working Group's requirements for this document have changed since the previous step.
- [ ] should report any changes in dependencies with other groups.
- [ ] should provide information about implementations known to the Working Group.

**Comment by ylafon** [comment]
A CfC would be good. I am checking if there are any new implication wrt the group charter but it should be fine (as in the past).

**Comment by marcoscaceres** [comment]
Link to CFC on GitHub https://github.com/w3c/image-resource/issues/17

**Comment by marcoscaceres** [comment]
Initial TAG feedback https://github.com/w3ctag/design-reviews/issues/490

**Comment by marcoscaceres** [comment]
We should see how the TAG review plays out a bit.

**Comment by marcoscaceres** [comment]
Looks like the TAG review completed without any objections.

**Comment by marcoscaceres** [comment]
@siusin, could you help us get this published as a FPWD?

**Comment by marcoscaceres** [comment]
https://w3c.github.io/image-resource/?specStatus=FPWD ... I guess we can add the Priv/Sec section after FWPD?

**Comment by siusin** [comment]
[Request sent](https://github.com/w3c/transitions/issues/242). Awaiting Director.

**Comment by marcoscaceres** [comment]
Approved 🎉, so closing.
