### ISSUE TITLE
Clipboard spec is failing to publish

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webappswg#31]
Getting following error: 

```
✗ Echidna failed to publish undefined
 for the following reasons:

   The file has been retrieved.
   The metadata have been extracted.
   The document failed Specberus.
 👎 Error code “latest-is-not-previous”.
     ⮡ cf https://www.w3.org/pubrules/doc/rules/?profile=WD#docIDFormat

More details are available here:

 https://labs.w3.org/echidna/api/status?id=9423cd51-eecf-465a-aa4c-ca4ebbe654e2

If you think you found a bug, please fill in and submit this issue:

 https://github.com/w3c/echidna/issues/new?title=Bug:%20%5BWHAT%5D&body=%5BEXPLANATION%5D%0A%0AFound%20while%20trying%20to%20publish%20%60tar%60%20(see%20the%20%5Bpublication%20job%5D(https%3A%2F%2Flabs.w3.org%2Fechidna%2Fapi%2Fstatus%3Fid%3D9423cd51-eecf-465a-aa4c-ca4ebbe654e2)).&labels=from-template

~ 3/26/2020, 3:04:11 AM

-- 
Echidna 1.14.9 (Specberus 4.1.6)
Copyright © 2014–2018 W3C — https://www.w3.org/
```

**Comment by marcoscaceres** [comment]
@siusin, any chance you could look into this?

**Comment by siusin** [comment]
Bikeshed has been ported to Python 3, so the builds will fail until we fix the script. I'll go through all the repos of the WebApps WG tomorrow to update the setting.

**Comment by marcoscaceres** [comment]
Thanks @siusin! really appreciate your help!

**Comment by siusin** [comment]
Thanks @marcoscaceres ! I've submitted a few PRs to fix the problem.

According to Dom's report, the CI config of the follow WICG repos also need to be updated. Do you have the write access to do so? Let us know if any help is needed.
"WICG/background-fetch"
"WICG/client-hints-infrastructure"
"WICG/element-timing"
"WICG/permissions-request"
"WICG/portals"
"WICG/priority-hints"
"WICG/purification"
"WICG/ResizeObserver"
"WICG/shape-detection-api"
"WICG/speech-api"
"WICG/ua-client-hints"
"WICG/webpackage"

**Comment by marcoscaceres** [comment]
Awesome! thank you for the speedy turnaround!
