### ISSUE TITLE
Add @saschanaz to WebAppWG members

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webappswg#36]
@siusin, I'm having trouble figuring out how to add @saschanaz to the WebApps WG members group... any chance you could take a look?

**Comment by siusin** [comment]
Hey @marcoscaceres , I've added @saschanaz to the WebApps WG GitHub team. Is him a Mozilla employee now? If yes, we may need to terminate his Invited Expert status and ask him to join the WG on behalf of Moz.

**Comment by saschanaz** [comment]
Changed my affiliation. That immediately removed me from all Working Groups 😲

**Comment by marcoscaceres** [comment]
@saschanaz, no problem. Just re-join and our AC rep will approve you.

**Comment by marcoscaceres** [comment]
Thanks again @siusin! Closing as done.
