### ISSUE TITLE
Create a new repo for "manifest-app-info"

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webappswg#37]
@siusin, could you please create up a new repo for us called "manifest-app-info"?

**Comment by siusin** [comment]
Repo created -> https://github.com/w3c/manifest-app-info

@marcoscaceres you should own the admin access to this repo, the WebApps WG team own write access.

**Comment by marcoscaceres** [comment]
Awesome! thank you. Btw I noticed the WebApps WG team membership is somewhat out of date... we should review that at some point.
