### ISSUE TITLE
Upgrade the WebApps WG GitHub team

### ISSUE THREAD

**Issue by siusin** [w3c/webappswg#38]
plh will create 3 new teams to help us manage the repos:

- w3c-group-groupID-chairs -- admin access
- w3c-group-groupID-members -- write access
- webapps-wg-extra -- write access (who hasn't formally joined the WG but contribute frequently)

**Comment by plehegar** [comment]
https://github.com/orgs/w3c/teams/w3c-group-114929-members
https://github.com/orgs/w3c/teams/w3c-group-114929-chairs

**Comment by marcoscaceres** [comment]
This was done.
