### ISSUE TITLE
Publish manifest-app-info as FPWD

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webappswg#39]
CFC sent:
https://github.com/w3c/manifest-app-info/issues/13

We need to request a shortname ... @siusin anything else? 

cc @aarongustafson

**Comment by siusin** [comment]
Thank you @marcoscaceres . I'll file a [transition request to the Director](https://github.com/w3c/transitions/issues) once the CfC is over, then we can publish the note in the group.

**Comment by marcoscaceres** [comment]
Ok cool, CFC is passed. @siusin let me know if you need anything spec wise.

**Comment by siusin** [comment]
TransReq sent -> https://github.com/w3c/transitions/issues/256

@marcoscaceres please add to the comments if you have any detail about the known implementation intention :)

**Comment by marcoscaceres** [comment]
Thanks again @siusin.
