### ISSUE TITLE
TPAC 2020 Agenda

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webappswg#40]
#### Registration
Please [register](https://www.w3.org/2002/09/wbs/35125/TPAC2020/) to attend.

##### Logistics

General meeting: 
  *  19 October 2020, 9PM to 11PM UTC ([timezone converter](https://www.timeanddate.com/worldclock/converter.html?iso=20201019T210000&p1=136&p2=224&p3=152&p4=179&p5=195)). 
  * **Zoom Meeting ID**: 959 0783 8530 - [password](https://lists.w3.org/Archives/Member/w3c-archive/2020Sep/0628.html) (member only)

IRC: #webapps https://www.w3.org/wiki/IRC - direct link https://irc.w3.org

##### Agenda 
Additional topics welcome: 

 * Welcome + introductions 
 * Aganda bashing
 * Reminder to create breakout sessions for next week. 
 * Status updates on each specs (5-10 mins each)
    * [Badging API](https://github.com/w3c/badging/issues/78)
    * [Clipboard APIs](https://github.com/w3c/clipboard-apis/issues/124)
    * [File API](https://github.com/w3c/FileAPI/issues/156)
    * [GamePad API](https://github.com/w3c/gamepad/issues/137)
    * [IndexedDB](https://github.com/w3c/IndexedDB/issues/338)
    * [Input Events](https://github.com/w3c/input-events/issues/111)
    * [Intersection Observer](https://github.com/w3c/IntersectionObserver/issues/435)
    * [Pointer Lock 2.0](https://github.com/w3c/pointerlock/issues/64)
    * [Push API](https://github.com/w3c/push-api/issues/326)
    * [Selection API](https://github.com/w3c/selection-api/issues/122)
    * [Screen Orientation API](https://github.com/w3c/screen-orientation/issues/199)
    * [UI Events](https://github.com/w3c/uievents/issues/268)
    * [Web App Manifest](https://github.com/w3c/manifest/issues/906) + ([Manifest App Info](https://w3c.github.io/manifest-app-info/))
    * [Web Share](https://github.com/w3c/web-share/issues/162)
    * [ARIA-in-HTML](https://github.com/w3c/html-aria/issues/233)
 * Required spec sections and guides 
   - using the GitHub labels to get review from horizontal groups.  
 * Process 2020 for spec editors
 * Pitch sessions
   - [nativeio](https://github.com/fivedots/nativeio-explainer)
 * General questions / feedback 

##### Breakout sessions
[Useful info](https://lists.w3.org/Archives/Public/public-webapps/2020JulSep/0033.html) if you are holding your own breakout session. See [breakout sessions calendar](https://calendar.google.com/calendar/u/0?cid=Y19tczEyajVndXFhczdnZmg5ZjRiN3YydGY1MEBncm91cC5jYWxlbmRhci5nb29nbGUuY29t). 

##### Minutes
[WebApps TPAC minutes](https://www.w3.org/2020/10/19-webapps-minutes.html)

**Comment by siusin** [comment]
Zoom Meeting ID: 959 0783 8530
Password: [click this](https://lists.w3.org/Archives/Member/w3c-archive/2020Sep/0628.html) [member-only]

**Comment by zcorpan** [comment]
from #435

I'd like to discuss these topics, in relation to lazy-loading in HTML:

- Allow dynamically changing rootMargin https://github.com/w3c/IntersectionObserver/issues/428
- Ability to have automatic rootMargin for all nested scroll containers https://github.com/w3c/IntersectionObserver/issues/431

**Comment by siusin** [comment]
Thanks, @zcorpan ! 

/cc @szager-chromium and @emilio.

**Comment by fivedots** [comment]
I would also like to discuss [NativeIO](github.com/fivedots/nativeio-explainer), our new storage API proposal.

In particular, it would be great to (very) quickly introduce it and gather any questions/feedback that might come up.

**Comment by hober** [comment]
> I would also like to discuss [NativeIO](https://github.com/fivedots/nativeio-explainer), our new storage API proposal.

Your link is broken (it's missing `https://`). I fixed it in this quote.

**Comment by aarongustafson** [comment]
@marcoscaceres Do you want me to talk about App Info in the manifest section too?

**Comment by Cupruminvictus** [comment]
Yes

pt., 16 paź 2020, 15:20 użytkownik Xiaoqian Wu <notifications@github.com>
napisał:

**Comment by marcoscaceres** [comment]
@aarongustafson, sure, we can quickly discuss it during the Manifest section.  

@fivedots, added a "pitch" section above. Depending on your timezone, we can move it earlier if need be.

**Comment by marcoscaceres** [comment]
Just a heads up that the original timezone converter link was off by 1 hour 😱 The meeting remains at 9PM to 11PM UTC, but just in case anyone was going off that, please recheck above.

**Comment by carmacleod** [comment]
Note that the ARIA-in-HTML link in the opening comment is wrong.
It should be: [ARIA in HTML](https://github.com/w3c/html-aria/issues/233)

**Comment by johanneswilm** [comment]
It looks like the link to the password doesn't work for me. In case I am not able to log in, please find the status update for the Input Events spec here: https://github.com/w3c/input-events/issues/111#issuecomment-710239251

**Comment by siusin** [comment]
@johanneswilm sent you the Zoom info by email. Sorry about it.

**Comment by LJWatson** [comment]
Thanks @carmacleod, corrected.

**Comment by adrianhopebailie** [comment]
This time slot (11pm - 1am local) was a difficult one for me to provide a report back on [Web Monetization](https://webmonetization.org) so sorry for not joining. 

I'll be presenting a progress report to the Web Payments WG on [Thursday](https://github.com/w3c/webpayments/wiki/2020-TPAC-WPWG-agenda#22-october) and there is a [breakout](https://www.w3.org/wiki/TPAC/2020/SessionIdeas#Revenue_Models_for_the_Web) proposed to address the topic of monetisation more generally (contrasting the WM API with other approaches and advertising and discussing the role of standards).

If anyone would like to be part of the panel in the breakout please let myself or @ali-spivak know ASAP

**Comment by marcoscaceres** [comment]
@adrianhopebailie, @ali-spivak, any chance you could send @sidvishnoi and I a cal invite? We'd like to join.
