### ISSUE TITLE
CFC: Separate Editing TF from WebApps WG

### ISSUE THREAD

**Issue by LJWatson** [w3c/webappswg#42]
This is a Call For Consensus (CFC) on  the following proposal: 

The co-chairs of WebApps and the co-chairs of the Editing Task Force (TF) propose that the Editing TF separate from WebApps, in order to become the (proposed) Editing WG.

Although the Editing TF is officially part of WebApps, it has been operating independently (and productively), with Grisha Lyukshin and Johannes Wilm as TF co-chairs. This proposal simply recognises this reality, and acknowledges that as an Editing WG the editing activity would have greater visibility and recognition at W3C.

It is expected that the proposed Editing WG will adopt the [Editing TF charter](https://github.com/w3c/editing/blob/gh-pages/CHARTER.md), and that the following specifications would move from WebApps to the new WG:

* Input Events Levels 1 and 2
* Clipboard API
* Selection API

If this CFC should not pass, or if the Advisory Committee should not support the formation of an Editing WG, then the Editing TF will remain part of WebApps.

If you support this proposal, add a "thumbs up" to this comment, or post a comment of your own.

If you do not support this proposal, add a "thumbs down" to this comment, or post a comment of your own.

It is important that your response is known, so please take a moment to add your reaction to this comment. W3C convention means that a lack of responses will be taken as silent support for the proposal, but it is much better when we know for sure.

Please do this by the end of your day on 24 January 2021. Thank you.

**Comment by LJWatson** [comment]
Thank you to everyone who responded. With multiple expressions of support and no objections, this CFC passes.

Next steps will be for the Editing WG to be proposed to the Advisory Committee (AC), and assuming the AC agrees with the proposal, all the editing activities will be migrated to the new WG and droppped from the WebApps charter in due course.

**Comment by siusin** [comment]
A draft charter of the future Editing WG -> https://github.com/w3c/editing/pull/276

All comments are welcome.
