### ISSUE TITLE
Indexed DB forgotten?

### ISSUE THREAD

**Issue by inexorabletash** [w3c/webappswg#43]
It's in the charter, but I noticed that Indexed DB is missing from both the README.md and https://w3c.github.io/webappswg/

Intentional? Accident? I assume an accident, but maybe I missed an announcement somewhere...

**Comment by marcoscaceres** [comment]
Total accident! Will fix.

**Comment by marcoscaceres** [comment]
@siusin, just checked on the TR listing and it seems that IDB is still associated with the old "Web *Platform* Working Group". Is that something you can update?

**Comment by siusin** [comment]
@marcoscaceres @inexorabletash we never published any new version of Indexed DB in the past few years, so it's not listed in the /TR (W3C Technical Report System). This can be fixed if you agree to publish a (First) Public Working Draft of IDB3. Shall we?

**Comment by inexorabletash** [comment]
SGTM

**Comment by siusin** [comment]
Thanks @inexorabletash !

@marcoscaceres @LJWatson could you start a CfC in the WebApps WG to publish IDB3?

**Comment by marcoscaceres** [comment]
>  could you start a CfC in the WebApps WG to publish IDB3?

done.

Closing in favor of https://github.com/w3c/IndexedDB/issues/348
