### ISSUE TITLE
Charter nit with contentEditable

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webappswg#5]
Someone ping me with regards to the charter: 
> not sure if it's a problem, but the way contentEditable is listed in the webapps charter is different from all the other specs -- the table near the top links straight to the spec, and there's no bit towards the bottom

@siusin, could you please take a look?

**Comment by siusin** [comment]
I guess it was because contentEditable has never been published as a WD, so it doesn't have the history of Call for Exclusion as the others do in the group.

@ylafon may know better ;)

**Comment by marcoscaceres** [comment]
Ok, yeah, that make sense. Still wish we’d sent that one to the WICG.

**Comment by siusin** [comment]
We can discuss with the editor in TPAC :)
