### ISSUE TITLE
Move Web Locks to Normative Specifications section

### ISSUE THREAD

**Issue by saschanaz** [w3c/webappswg#73]
(Following #70)

Since Google already shipped it and Mozilla is now prototyping it ([thread]( https://groups.google.com/a/mozilla.org/g/dev-platform/c/qprlUIF0H48)), it's probably time to consider taking it as a normative spec.

cc @tantek

**Comment by marcoscaceres** [comment]
Absolutely. It’s already in our updated as something we plan to adopt: 

https://github.com/w3c/webappswg/blob/1bfaf6bfbc2ed9e320a5d64b16dfe384b82eb77c/charter/draft-charter-2021.html#L549

In the meantime, please keep working on the spec and make sure it’s in the best shape possible for us to bring over to the W3C.
