### ISSUE TITLE
Update WG homepage

### ISSUE THREAD

**Issue by LJWatson** [w3c/webappswg#74]
The [WebApps homepage](https://www.w3.org/2019/webapps/) still shows the Editing WG specs, and also the HTML AAM that is now back in the ARIA WG.

**Comment by marcoscaceres** [comment]
Hi @plehegar - could you provide me with instructions on how to regenerate the homepage snapshot? Happy to maintain it so we don't need to bug you 🙏.

**Comment by siusin** [comment]
@plehegar could you do a poll for the WebApps WG homepage to update the data? thanks

**Comment by plehegar** [comment]
Any reason why we can't switch to use https://www.w3.org/groups/wg/webapps ?

**Comment by plehegar** [comment]
cc @siusin

**Comment by siusin** [comment]
Of course. I will switch to /groups if I don't hear any objections before Wednesday.

**Comment by siusin** [comment]
Thanks to Vivien's help, now we have switched to https://www.w3.org/groups/wg/webapps.

**Comment by LJWatson** [comment]
Hurrah! Thanks @siusin  and @vivienlacourba
