### ISSUE TITLE
TPAC 2022 - Call for topics and session planning

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webappswg#87]
The WebApps WG is meeting 12th-13th September (Monday/Tuesday). 

Due to TPAC being hybrid, we need to be quite organized with timing of each session happening for WebApps WG. 

As reminder, here are the specs of the working group:

 * [ARIA in HTML](https://www.w3.org/TR/html-aria/) - [repository](https://github.com/w3c/html-aria/)
 * [Badging API](https://w3c.github.io/badging/) - [repository](https://github.com/w3c/badging)
 * [File API](https://www.w3.org/TR/FileAPI/) - [repository](https://github.com/w3c/FileAPI/)
 * [Gamepad API](https://www.w3.org/TR/gamepad) - [repository](https://github.com/w3c/gamepad/)
 * [Image Resource](https://www.w3.org/TR/image-resource) - [repository](https://github.com/w3c/image-resource/)
 * [IndexedDB](https://www.w3.org/TR/IndexedDB/) - [repository](https://github.com/w3c/IndexedDB/) 
 * [Intersection Observer](https://www.w3.org/TR/intersection-observer/) - [repository](https://github.com/w3c/IntersectionObserver/)
 * [Pointer Lock](https://www.w3.org/TR/pointerlock) -[repository](https://github.com/w3c/pointerlock/)
 * [Push API](https://www.w3.org/TR/push-api) - [repository](https://github.com/w3c/push-api/)
 * [Screen Orientation API](https://www.w3.org/TR/screen-orientation/) - [repository](https://github.com/w3c/screen-orientation/)
 * [UI Events](https://www.w3.org/TR/uievents) - [repository](https://github.com/w3c/uievents/)
 * [Web Locks](https://w3c.github.io/web-locks/) - [https://github.com/w3c/web-locks/]
 * [Web App Manifest](https://www.w3.org/TR/manifest) - [repository](https://github.com/w3c/manifest/)
 * [Web App Manifest - Application Information](https://github.com/w3c/manifest-app-info)
 * [Web Share](https://www.w3.org/TR/web-share) - [repository](https://github.com/w3c/web-share/)

Could folks (Editors in particular) indicate if they would like to meet? All participants, for each spec, please link to appropriate issue you want to discuss from the above repositories. If your **issue doesn't exist, please create it and provide as much detail as possible**.  

Please be mindful that we can only allocate around ~1 hour per specification. So, Editors, please triage your issues to maximize the short time we have. 

If you are participating remotely, please let us know your preferred time (in PST/Vancouver's time) so we can best try to accommodate you. We will try to give you priority in scheduling.

**Comment by nondebug** [comment]
For Gamepad API I'd like to discuss [BFCache integration](https://github.com/w3c/gamepad/issues/149), especially around the handling of connection/disconnection events since this has implications for other device APIs (WebUSB, Web Bluetooth, WebHID, Web Serial, maybe others?)

**Comment by dmurph** [comment]
I think we would also like to chat about how we plan on adding new display modes to the spec, especially incubation display modes (e.g. https://wicg.github.io/window-controls-overlay/#addition-of-window-controls-overlay-to-the-manifest)

**Comment by pma-90** [comment]
> For Gamepad API I'd like to discuss [BFCache integration](https://github.com/w3c/gamepad/issues/149), especially around the handling of connection/disconnection events since this has implications for other device APIs (WebUSB, Web Bluetooth, WebHID, Web Serial, maybe others?)
> 
> 
> 
>

**Comment by marcoscaceres** [comment]
closing as done.
