### ISSUE TITLE
WebApps agenda TPAC 2022

### ISSUE THREAD

**Issue by LJWatson** [w3c/webappswg#88]
[TPAC 2022 ](https://www.w3.org/2022/09/TPAC/) is hybrid this year. WebApps will meet in Vancouver on [12 and 13 September](https://www.w3.org/calendar/tpac2022/). Please [register](https://www.w3.org/2022/09/TPAC/registration.html) if you plan to attend in person or remotely.

This agenda will be updated in this comment. Requests for agenda time should be made on #87.

#### Monday 12 September
All times are in Pacific Daylight Time (PDT):

* 9AM: meeting start
* 10:30AM: break
* 11AM: meeting resumes
* 12:30PM: lunch
* 1:30PM: meeting resumes
* 3PM: break
* 4PM: meeting resumes
* 5PM: meeting ends

#### Agenda Tuesday 13 September
All times are in Pacific Daylight Time (PDT):

* 9AM: meeting start
* 10:30AM: break
* 11AM: meeting resumes
* 12:30PM: lunch
* 1:30PM: meeting resumes
* 3PM: break
* 4PM: meeting resumes
* 5PM: meeting ends

**Comment by marcoscaceres** [comment]
Moved this to the wiki https://github.com/w3c/webappswg/wiki/TPAC-2022

**Comment by marcoscaceres** [comment]
Please update the wiki instead: https://github.com/w3c/webappswg/wiki/TPAC-2022

**Comment by LJWatson** [comment]
Can you update the link in the official TPAC calendar/meeting info when you get a moment?

**Comment by marcoscaceres** [comment]
yep, thanks for the reminder @LJWatson. Already done.
