### ISSUE TITLE
Explore the possibility of doing more joint deliverables with DAS

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webappswg#90]
A few of us would like to explore the possibility of doing more joint deliverables with the Device and Sensors WG (DAS). In particular, it would be great to jointly work on:

 * [Screen Wake Lock API](https://www.w3.org/TR/screen-wake-lock/) 
 * [DeviceOrientation Event specification](https://www.w3.org/TR/orientation-event/) 

And possibly some others, but those would be a good start. 

I've [sent a PR](https://github.com/w3c/webappswg/pull/89) to update the WebApps Charter. 

The working group already has one joint deliverable with DAS: the Contacts Picker API. 

Having the above specs as joint deliverables would provide more possibility for input by a larger set of members.   

cc @reillyeon, @plehegar, @anssiko, @tantek.

**Comment by anssiko** [comment]
Thanks @marcoscaceres. Accordingly, I've opened an issue in the DAS WG charter repo https://github.com/w3c/das-charter/issues/123 to solicit input on this proposal from the DAS WG point of view and track respective updates.

Personally, I look forward to an even more fruitful collaboration in this device-centric web capabilities space.

**Comment by anssiko** [comment]
@marcoscaceres https://github.com/w3c/das-charter/pull/126

**Comment by anssiko** [comment]
@marcoscaceres @LJWatson, the DAS WG has now carefully reviewed this proposal and suggest the following scope for our joint deliverables slightly adjusted from the earlier expectations: https://github.com/w3c/das-charter/pull/126

Please let us know whether the WebApps WG would like to pursue this joint effort forward. The DAS WG participants are looking forward to an expanded, fruitful collaboration in this device-centric web capabilities space with all the WebApps WG participants.

cc @reillyeon

**Comment by marcoscaceres** [comment]
Still interested, but need a little bit more time.

**Comment by marcoscaceres** [comment]
Closing as we now have the joint deliverables.
