### ISSUE TITLE
TPAC 2023 -  Call for topics 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webappswg#91]
TPAC 2023 will be held from 11 to 15 September 2023, with a main in-person hub at Melia Sevilla Hotel, in Sevilla, Spain.

**tl;dr:** _please leave a comment below on your topic and how long you need (90 minute or 2-hour slot)._ 

As last year, we are adapting our format to a hybrid mode and planning to build a dynamic meeting.

Here is the projected schedule (still to be confirmed):

The schedule of the week should be as follows:

- Monday 11 September
- Tuesday 12 September. 

In order to build a dynamic meeting to bring more cross participation and interactions, we will work this year with set slots. Each group will be able to ask for 90 minute and/or 2-hour slots.

**Comment by humeranoor** [comment]
Dear team, 
Here is our proposal for the breakout session on Wednesday 13th September:

**Topic: Sustainability in the digital world**
**Proposal type:** open discussion
**Slot Duration:** 90 min
**By:** [Cornelius Witt](mailto:c.witt@eyeo.com) and [Humera Noor Minhas](mailto:h.minhas@eyeo.com)
**Company:** eyeo GmbH 
**Website:** https://eyeo.com/
**Overview:**
When we speak about sustainability and climate change, we think about long-haul flights and solar panels. We do not realize that our day-to-day digital behavior, like mindless scrolling, dark vs bright backgrounds, and the online advertisements on the pages we visit contributes to our carbon footprint as well. This open discussion is about how we, the people on the web, can build products that are sustainable and positively impact the user behavior in a way that contributes to a greener environment.

**Comment by LJWatson** [comment]
Thank you @humeranoor, but this issue is for breakouts during the WebApps WG meetings (which will either be on the Mon/Tue or Thu/Fri), not for the Wednesday breakout sessions.

**Comment by humeranoor** [comment]
Ouch, my bad - and I was wondering why there is not much happening on this page 😬 
Can you tell me where to submit proposals for Wednesday breakout sessions? I don't see anything [here](https://www.w3.org/wiki/TPAC/2023).

**Comment by LJWatson** [comment]
The official call doesn't usually go out until after registrations has opened AIRC, but it looks like there is a [breakouts wiki page](https://www.w3.org/wiki/TPAC/2023/SessionIdeas) available. Also worth checking the [official TPAC info](https://www.w3.org/2023/09/TPAC/) from time to time too.

**Comment by humeranoor** [comment]
Thank you for sharing @LJWatson.
This breakouts wiki page is new - I didn't know about it.
Now I know :)

I'll wait for the registrations. 
Thanks a lot.

**Comment by marcoscaceres** [comment]
For Web Manifest, a few of us would like to discuss: 

 * Launch events
 * Declarative install solution (or BIP again)
 * navigator.standalone and some CSS things to compliment that
 * Possibly something else 

Cc @b1tr0t, @dmurph

**Comment by marcoscaceres** [comment]
Gamepad API folks would like to meet for 1-2 hours to chat about: 

 * haptics 
 * finishing the model for the spec
 * folding in more of the extension 
 * Possibly other topics

**Comment by cabanier** [comment]
> Gamepad API folks would like to meet for 1-2 hours to chat about:
> 
> * haptics
> * finishing the model for the spec
> * folding in more of the extension
> * Possibly other topics

The Immersive group will meet Monday, Tuesday and Friday according to the schedule. We can do a joint meeting any of those days.

**Comment by tomayac** [comment]
While we all agree on the OPFS, the vendors have differing opinions on dealing with files in the user-visible file system, like [File Handling](https://github.com/WICG/file-handling/blob/main/explainer.md), [drag and drop integration](https://wicg.github.io/file-system-access/#dom-datatransferitem-getasfilesystemhandle), and the various [picker methods](https://wicg.github.io/file-system-access/#local-filesystem). Would it be worthwhile to discuss this again, especially in the light of macOS Sonoma's support for web apps?

**Comment by dmurph** [comment]
(copying from post in https://github.com/w3c/manifest/issues/1093)

@marcoscaceres confirmation on the list you wrote, those are all important for us to talk about. Can we get those topics on the schedule? I'm thinking:

- 1 hour - **launch events / handling / data handling / file handling / etc**
  - I expect we will bring use-cases here and API proposals, and discuss about API shape, use-cases, etc.
  - Goal: Come to tentative agreement on what the following would look like
    - declarative API (currently implemented as launch handling & file handling in Chromium, but could be changed) and
    - JS API (not implemented in Chromium yet), like the existing service worker launch event proposal, or something different.
- 1 hour - **install, imperative install, BIP, etc**
  - I expect we will bring use-cases and partner requests, and outline existing solutions & new proposals like navigator.install.
  - Goal: Come to direction agreement (or acknowledged disagreement) on where we want installation & developer controls on installation to go in the future.
- 15-30 min: **detecting install / navigator.standalone**
  - Goal: Determine if this is acceptable for the platform, and if so, what the API shape might be
  - [initial doc](https://docs.google.com/document/d/1fSuVG7MHy6ugGbSLfW6V--y8y5NbRa-OZvVE-Tf2T30/edit?usp=sharing) I created
- 30-60 mins **Updates: Recap on last TPAC algorithm, re-alignment of goals**
  - How is safari thinking about updating security sensitive members & spoofing risk?
- ?? mins **Isolation**
  - @mgiuca and @reillyeon what time do you think we would need to chat about this? Goal of toipcs?
  - Discuss problems that arise if user agents create an isolated environment for installed apps, with regards to external navigation, Oauth being the biggest problem.
  - Discuss the possibility of creating standards around (and possibly APIs around) which storage partition to open certain URLs in (rather than relying on unspecified heuristics).


Minor topics (15 mins each, if needed)
- **Window controls overlay** - Any interest / questions from other user agents?
- **protocol handlers**
- Why did Safari gate notifications on installation?
- **notifications** - Issues that chromium is currently seeing (although Peter won't be around, so not sure if we can talk about solutions)
- **Menu bar API** for mac menu bar.

What do you think about those topics and goals? Any changes?

**Comment by marcoscaceres** [comment]
We should chat generally about the "Expectations of Editors" and what that means, and when those expectations are not met.

**Comment by marcoscaceres** [comment]
We should have a joint meeting with the i18n Folks about web manifest.

**Comment by marcoscaceres** [comment]
WebKit folks would like to again discuss a more efficient solution for Push notifications. This would be a follow up to what we discussed at last year's TPAC.

**Comment by marcoscaceres** [comment]
We should set set time aside for status on joint deliverables with DAS. Maybe @reillyeon and I could a quick presentation about what we plan on collaborating on?

**Comment by marcoscaceres** [comment]
@cabanier, hey, let's book in 20 minutes on Tuesday late afternoon. That way Ben from Microsoft can join.

**Comment by marcoscaceres** [comment]
@tomayac, let's discuss your proposal on Tuesday and mix it in generally with the stuff that @dmurph listed above. Can you coordinate with him to make sure it's covered?

**Comment by LJWatson** [comment]
Everyone, last call for meeting topic/time for TPAC. If you haven't already, please post a comment here by end of day on Friday 4 August. Thanks.

**Comment by tomayac** [comment]
@dmurph, based on https://github.com/w3c/webappswg/issues/91#issuecomment-1660016533, what do you think of this plan, which builds upon your bullets from https://github.com/w3c/webappswg/issues/91#issuecomment-1642897091:

- 1 hour - **launch events / url handling / link handling / data handling / file handling / etc**
  - I expect we will bring use-cases here and API proposals, and discuss about API shape, use-cases, etc.
  - Goal: Come to tentative agreement on what the following would look like
    - declarative API (currently implemented as launch handling & file handling in Chromium, but could be changed) and
    - JS API (not implemented in Chromium yet), like the existing service worker launch event proposal, or something different.
    - Can we get at least directional alignment on dealing with files in the user-visible file system, focusing the discussion on the following APIs:
      - [File Handling](https://github.com/WICG/file-handling/blob/main/explainer.md)
      - [Drag and drop integration](https://wicg.github.io/file-system-access/#dom-datatransferitem-getasfilesystemhandle)
      - [Picker methods](https://wicg.github.io/file-system-access/#local-filesystem)

1 hour may be a stretch given the complexity of some of the topics.

**Comment by dmurph** [comment]
@tomayac I agree 1 hour might be a stretch. Hopefully I can help with prework here. Maybe we expect possible overflow of this one?

**Comment by marcoscaceres** [comment]
Ok, locking in 5pm on Tuesday to talk about haptics across both groups.

**Comment by a-sully** [comment]
> * Can we get at least directional alignment on dealing with files in the user-visible file system, focusing the discussion on the following APIs: 
>   * [File Handling](https://github.com/WICG/file-handling/blob/main/explainer.md)
>   * [Drag and drop integration](https://wicg.github.io/file-system-access/#dom-datatransferitem-getasfilesystemhandle)
>   * [Picker methods](https://wicg.github.io/file-system-access/#local-filesystem)

@tomayac shall we split this discussion off into a separate session on file system? There's enough material on that topic alone to cover an hour or more. And that would give the rest of your proposed agenda room to breath :)

**Comment by a-sully** [comment]
....though where exactly to talk about file system is up for discussion... Last year we didn't talk about it with the WAWG, but had [separate whatwg and WICG discussions](https://github.com/whatwg/fs/issues/45) for the respective [whatwg](https://github.com/whatwg/fs/) and [WICG](https://github.com/WICG/file-system-access) halves of the spec... but the WAWG is arguably the place this should be discussed anyways (as @tomayac mentioned in https://github.com/w3c/webappswg/issues/91#issuecomment-1640138703)

Open to suggestions from the organizers!

**Comment by diekus** [comment]
30-45 minutes to chat about `Web Install API`, declarative way of installing web apps. Also adding `AttributionInfo` to the mix since it is related.

**Comment by LJWatson** [comment]
@Dikis this the same as @tomayac mentioned in https://github.com/w3c/webappswg/issues/91#ref-issue-1831631950?

**Comment by LJWatson** [comment]
We've posted the [WebApps TPAC 2023 agenda](https://github.com/w3c/webappswg/wiki/TPAC-2023).

We have a crammed schedule for both days. We may be able to fit one or two more things in, but it'll mean running a really tight schedule the whole time.

Looking forward to catching up with everyone then 😊

**Comment by tomayac** [comment]
> @Dikis this the same as @tomayac mentioned in [#91 (reference)](https://github.com/w3c/webappswg/issues/91#ref-issue-1831631950)?

(Correcting @Dikis to @diekus.)

**Comment by LJWatson** [comment]
>(Correcting...

Oops! I'm sorry. My bad. Thanks for catching that.

**Comment by a-sully** [comment]
Following up on https://github.com/w3c/webappswg/issues/91#issuecomment-1664714723 - I'd like to discuss the APIs @tomayac listed in that comment (relating to File System) with this working group. 30 minutes should be sufficient if we limit the scope to just these few topics. Any chance we can make room on the agenda? Thanks!

**Comment by marcoscaceres** [comment]
closing in prep to start planning for 2024
