### ISSUE TITLE
Panel distance API proposal for VR

### ISSUE THREAD

**Issue by brycethomas** [w3c/webappswg#93]
I'd like to propose a new API which exposes the (virtual) distance between the viewer and the Browser panel in VR.  For example, the Browser panel may open at a virtual distance of 2 meters from the viewer.  The user takes one step forward, and the viewing distance is now 1.5 meters.  An example use-case is transitioning a page between a summary and detailed view (e.g. today's weather vs. weekly forecast) as the user gets closer to the panel.  Has anything of this sort been proposed in the past?  If not, is this an appropriate venue for such a proposal?

**Comment by marcoscaceres** [comment]
Hi @brycethomas! Thanks for the proposal. Sorry to give you the run around, but would you mind posting it the Immersive Web group instead? They have a proposals repo and are best placed to help incubate your proposal. 
https://github.com/immersive-web/proposals
