### ISSUE TITLE
ImageResource spec (shelve?)

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webappswg#95]
We might need to figure out what to do about the ImageResource spec and if it's something we want to move forward with... it was being used with Payment Handler at one point (and might still be) and maybe some other spec. Need to check. However, if it doesn't get much traction, we could just fold it into whatever spec is using it.

**Comment by saschanaz** [comment]
Per webref it's being used in:

* Background Fetch (WICG): https://wicg.github.io/background-fetch/#background-fetch-manager
* Content Index (WICG): https://wicg.github.io/content-index/spec/#content-index
* Secure Payment Confirmation: https://w3c.github.io/secure-payment-confirmation/#sctn-steps-to-check-if-a-payment-can-be-made
* Web Application Manifest: https://www.w3.org/TR/appmanifest/#dfn-process-image-resources (which is then again used by miniapp-manifest and manifest-incubations)
  * Application Information: https://w3c.github.io/manifest-app-info/#screenshot-object-and-its-members

**Comment by marcoscaceres** [comment]
Ah great. Thanks for looking that up @saschanaz. Closing.
