### ISSUE TITLE
WebApps WG 2023 Rechartering

### ISSUE THREAD

**Issue by siusin** [w3c/webappswg#97]
Proposed Draft Charter: https://w3c.github.io/webappswg/charter/draft-charter-2023.html

Todos:

- [ ] update the Estimated Completion Dates / Milestones
- [x] a plan for ImageResource spec? Also see #95 
- [x] add joint deliverables with DAS. Also see #89 
- [x] remove redundancy from [working-mode](https://w3c.github.io/webappswg/charter/draft-charter-2023.html#working-mode) section?

**Comment by marcoscaceres** [comment]
@siusin, for the join deliverables, did I understand correctly that you have some tooling that will help add those in place?

**Comment by marcoscaceres** [comment]
oh! never mind! they are already there. 😊 Thank you!

**Comment by marcoscaceres** [comment]
@siusin, looks like ImageResouce is being used [in various places](https://github.com/w3c/webappswg/issues/95#issuecomment-1529412286), so can stay.

**Comment by marcoscaceres** [comment]
Ok, cool. I've sent the PRs for the scope of the new deliverables and the removing the redundancy between working mode and communication. 

@siusin, feel free to sent a PR with any dates you see fit for "Estimated Completion Dates / Milestones".

**Comment by marcoscaceres** [comment]
Closing this as done.
